import type {
  EconomicEdge,
  EconomicNode,
  ImpactPrediction,
  MacroIndicator,
  NewsEvent,
  VolatilitySignal,
} from "@/types";

export const DEMO_NODES: EconomicNode[] = [
  { id: "n1", type: "country", name: "China", symbol: "CN", metadata: {} },
  { id: "n2", type: "country", name: "United States", symbol: "US", metadata: {} },
  { id: "n3", type: "commodity", name: "Iron Ore", symbol: "IRON", metadata: {} },
  { id: "n4", type: "commodity", name: "Copper", symbol: "HG", metadata: {} },
  { id: "n5", type: "commodity", name: "Crude Oil", symbol: "CL", metadata: {} },
  { id: "n6", type: "sector", name: "Mining", symbol: null, metadata: {} },
  { id: "n7", type: "sector", name: "Airlines", symbol: null, metadata: {} },
  { id: "n8", type: "sector", name: "Banks", symbol: null, metadata: {} },
  { id: "n9", type: "sector", name: "Housing", symbol: null, metadata: {} },
  { id: "n10", type: "sector", name: "Retail", symbol: null, metadata: {} },
  { id: "n11", type: "company", name: "BHP Group", symbol: "BHP", metadata: {} },
  { id: "n12", type: "company", name: "Freeport-McMoRan", symbol: "FCX", metadata: {} },
  { id: "n13", type: "company", name: "Delta Air Lines", symbol: "DAL", metadata: {} },
  { id: "n14", type: "company", name: "JPMorgan Chase", symbol: "JPM", metadata: {} },
  { id: "n15", type: "rate", name: "Federal Funds Rate", symbol: "FEDFUNDS", metadata: {} },
  { id: "n16", type: "rate", name: "VIX", symbol: "VIXCLS", metadata: {} },
  { id: "n17", type: "industry", name: "Steel Production", symbol: null, metadata: {} },
  { id: "n18", type: "industry", name: "Shipping", symbol: null, metadata: {} },
  { id: "n19", type: "currency", name: "Australian Dollar", symbol: "AUD", metadata: {} },
  { id: "n20", type: "etf", name: "XLE Energy ETF", symbol: "XLE", metadata: {} },
];

export const DEMO_EDGES: EconomicEdge[] = [
  { id: "e1", source_id: "n1", target_id: "n3", relationship_type: "demand", strength: 0.92, confidence: 0.88, historical_accuracy: 0.85, time_horizon_days: 60, description: "China stimulus drives iron ore demand" },
  { id: "e2", source_id: "n1", target_id: "n4", relationship_type: "demand", strength: 0.88, confidence: 0.85, historical_accuracy: 0.82, time_horizon_days: 45, description: "Infrastructure spending lifts copper" },
  { id: "e3", source_id: "n3", target_id: "n6", relationship_type: "supply_chain", strength: 0.9, confidence: 0.9, historical_accuracy: 0.88, time_horizon_days: 30, description: "Iron ore feeds mining sector" },
  { id: "e4", source_id: "n4", target_id: "n6", relationship_type: "supply_chain", strength: 0.85, confidence: 0.87, historical_accuracy: 0.84, time_horizon_days: 30, description: "Copper demand supports miners" },
  { id: "e5", source_id: "n6", target_id: "n11", relationship_type: "earnings", strength: 0.8, confidence: 0.82, historical_accuracy: 0.78, time_horizon_days: 45, description: "Mining boom lifts BHP" },
  { id: "e6", source_id: "n6", target_id: "n12", relationship_type: "earnings", strength: 0.78, confidence: 0.8, historical_accuracy: 0.76, time_horizon_days: 45, description: "Copper prices drive FCX" },
  { id: "e7", source_id: "n5", target_id: "n7", relationship_type: "cost_pressure", strength: 0.85, confidence: 0.9, historical_accuracy: 0.86, time_horizon_days: 14, description: "Oil prices hit airline margins" },
  { id: "e8", source_id: "n7", target_id: "n13", relationship_type: "earnings", strength: 0.75, confidence: 0.8, historical_accuracy: 0.74, time_horizon_days: 30, description: "Fuel costs impact Delta" },
  { id: "e9", source_id: "n5", target_id: "n20", relationship_type: "correlation", strength: 0.82, confidence: 0.88, historical_accuracy: 0.8, time_horizon_days: 7, description: "Oil moves energy ETF" },
  { id: "e10", source_id: "n15", target_id: "n8", relationship_type: "policy", strength: 0.9, confidence: 0.92, historical_accuracy: 0.89, time_horizon_days: 90, description: "Rate hikes affect bank margins" },
  { id: "e11", source_id: "n8", target_id: "n9", relationship_type: "lending", strength: 0.85, confidence: 0.87, historical_accuracy: 0.83, time_horizon_days: 60, description: "Banks finance housing" },
  { id: "e12", source_id: "n9", target_id: "n10", relationship_type: "wealth_effect", strength: 0.7, confidence: 0.75, historical_accuracy: 0.72, time_horizon_days: 90, description: "Housing wealth drives retail" },
  { id: "e13", source_id: "n1", target_id: "n17", relationship_type: "demand", strength: 0.86, confidence: 0.84, historical_accuracy: 0.8, time_horizon_days: 45, description: "China drives steel demand" },
  { id: "e14", source_id: "n17", target_id: "n3", relationship_type: "input", strength: 0.88, confidence: 0.86, historical_accuracy: 0.84, time_horizon_days: 30, description: "Steel needs iron ore" },
  { id: "e15", source_id: "n1", target_id: "n18", relationship_type: "demand", strength: 0.8, confidence: 0.78, historical_accuracy: 0.75, time_horizon_days: 60, description: "Export demand lifts shipping" },
  { id: "e16", source_id: "n4", target_id: "n19", relationship_type: "currency_link", strength: 0.72, confidence: 0.7, historical_accuracy: 0.68, time_horizon_days: 30, description: "Copper lifts commodity currencies" },
  { id: "e17", source_id: "n2", target_id: "n15", relationship_type: "policy", strength: 0.95, confidence: 0.95, historical_accuracy: 0.92, time_horizon_days: 180, description: "Fed sets rates" },
  { id: "e18", source_id: "n15", target_id: "n16", relationship_type: "volatility", strength: 0.75, confidence: 0.8, historical_accuracy: 0.77, time_horizon_days: 14, description: "Rate uncertainty lifts VIX" },
];

export const DEMO_NEWS: NewsEvent[] = [
  {
    id: "news1",
    title: "China announces major infrastructure stimulus package",
    summary: "Beijing unveils $500B infrastructure spending focused on urban development and green energy projects.",
    source: "Reuters",
    url: "https://example.com/china-stimulus",
    published_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    impact_score: 92,
    confidence_score: 85,
    urgency_score: 88,
    economic_importance: 95,
    entities: { countries: ["China"], commodities: ["Iron Ore", "Copper"], sectors: ["Mining", "Steel"] },
    processed: true,
  },
  {
    id: "news2",
    title: "Fed signals potential rate pause amid cooling inflation",
    summary: "Federal Reserve officials hint at holding rates steady as CPI shows continued moderation.",
    source: "Bloomberg",
    url: "https://example.com/fed-pause",
    published_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    impact_score: 88,
    confidence_score: 82,
    urgency_score: 75,
    economic_importance: 90,
    entities: { countries: ["United States"], sectors: ["Banks", "Housing"] },
    processed: true,
  },
  {
    id: "news3",
    title: "OPEC+ extends production cuts through Q3",
    summary: "Oil producers agree to maintain supply restrictions, pushing crude above $85/barrel.",
    source: "CNBC",
    url: "https://example.com/opec-cuts",
    published_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    impact_score: 85,
    confidence_score: 90,
    urgency_score: 80,
    economic_importance: 87,
    entities: { commodities: ["Crude Oil"], sectors: ["Airlines", "Energy"], tickers: ["DAL", "XLE"] },
    processed: true,
  },
  {
    id: "news4",
    title: "US housing starts fall 8% as mortgage rates remain elevated",
    summary: "New residential construction declines for third consecutive month amid 7% mortgage rates.",
    source: "Financial Times",
    url: "https://example.com/housing-starts",
    published_at: new Date(Date.now() - 12 * 3600000).toISOString(),
    impact_score: 78,
    confidence_score: 88,
    urgency_score: 65,
    economic_importance: 82,
    entities: { countries: ["United States"], sectors: ["Housing", "Retail", "Banks"] },
    processed: true,
  },
];

export const DEMO_IMPACTS: ImpactPrediction[] = [
  { id: "i1", news_event_id: "news1", affected_node_id: "n3", effect_order: 1, direction: "positive", probability: 0.88, reasoning: "Direct demand surge for iron ore from infrastructure buildout", time_horizon_days: 30, node: DEMO_NODES[2] },
  { id: "i2", news_event_id: "news1", affected_node_id: "n4", effect_order: 1, direction: "positive", probability: 0.85, reasoning: "Green energy projects require significant copper wiring", time_horizon_days: 45, node: DEMO_NODES[3] },
  { id: "i3", news_event_id: "news1", affected_node_id: "n6", effect_order: 2, direction: "positive", probability: 0.8, reasoning: "Commodity demand flows through to mining sector revenues", time_horizon_days: 60, node: DEMO_NODES[5] },
  { id: "i4", news_event_id: "news1", affected_node_id: "n11", effect_order: 3, direction: "positive", probability: 0.72, reasoning: "BHP benefits as largest diversified miner with China exposure", time_horizon_days: 90, node: DEMO_NODES[10] },
  { id: "i5", news_event_id: "news2", affected_node_id: "n15", effect_order: 1, direction: "neutral", probability: 0.82, reasoning: "Rate pause signal reduces near-term policy uncertainty", time_horizon_days: 30, node: DEMO_NODES[14] },
  { id: "i6", news_event_id: "news2", affected_node_id: "n8", effect_order: 2, direction: "positive", probability: 0.75, reasoning: "Stable rates support bank net interest margins", time_horizon_days: 60, node: DEMO_NODES[7] },
  { id: "i7", news_event_id: "news2", affected_node_id: "n9", effect_order: 2, direction: "positive", probability: 0.7, reasoning: "Lower mortgage rates could revive housing demand", time_horizon_days: 90, node: DEMO_NODES[8] },
  { id: "i8", news_event_id: "news3", affected_node_id: "n5", effect_order: 1, direction: "positive", probability: 0.9, reasoning: "Supply cuts directly support crude oil prices", time_horizon_days: 14, node: DEMO_NODES[4] },
  { id: "i9", news_event_id: "news3", affected_node_id: "n7", effect_order: 2, direction: "negative", probability: 0.82, reasoning: "Higher fuel costs compress airline margins", time_horizon_days: 30, node: DEMO_NODES[6] },
  { id: "i10", news_event_id: "news3", affected_node_id: "n13", effect_order: 3, direction: "negative", probability: 0.7, reasoning: "Delta particularly exposed to jet fuel cost increases", time_horizon_days: 45, node: DEMO_NODES[12] },
];

export const DEMO_VOLATILITY: VolatilitySignal[] = [
  { id: "v1", node_id: "n11", news_event_id: "news1", signal_type: "opportunity", hv_20d: 28.5, vix_percentile: 35, macro_risk_score: 72, volatility_opportunity_score: 85, reasoning: "China stimulus not yet priced into BHP options; HV below macro risk level", node: DEMO_NODES[10] },
  { id: "v2", node_id: "n12", news_event_id: "news1", signal_type: "opportunity", hv_20d: 32.1, vix_percentile: 35, macro_risk_score: 70, volatility_opportunity_score: 82, reasoning: "Copper demand surge likely underpriced; FCX calls cheap relative to catalyst", node: DEMO_NODES[11] },
  { id: "v3", node_id: "n13", news_event_id: "news3", signal_type: "opportunity", hv_20d: 24.8, vix_percentile: 35, macro_risk_score: 68, volatility_opportunity_score: 78, reasoning: "Oil spike creates airline downside not fully reflected in put premiums", node: DEMO_NODES[12] },
  { id: "v4", node_id: "n14", news_event_id: "news2", signal_type: "opportunity", hv_20d: 18.2, vix_percentile: 35, macro_risk_score: 55, volatility_opportunity_score: 65, reasoning: "Rate pause catalyst with low HV — potential straddle on FOMC decision", node: DEMO_NODES[13] },
];

export const DEMO_MACRO: MacroIndicator[] = [
  { seriesId: "VIXCLS", label: "VIX", value: 16.8, change: -1.2, unit: "index" },
  { seriesId: "FEDFUNDS", label: "Fed Funds Rate", value: 5.33, change: 0, unit: "%" },
  { seriesId: "CPIAUCSL", label: "CPI (YoY)", value: 3.2, change: -0.1, unit: "%" },
  { seriesId: "DGS10", label: "10Y Treasury", value: 4.28, change: -0.05, unit: "%" },
];
